name: KWYK_Github_workflow
on:
  push:
    branches:
      - 'release/v[1-9]?[0-9]+.[0-9]+[1-9]?'

jobs:
  deploy_golang_app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
